### ISSUE TITLE
line breaks get dropped

### ISSUE THREAD

**Issue by aaronkaplan** [CZ-NIC/envelope#4]
I am trying to send a mail this way:

```python
body = """
  Some very long mail
  With line breaks
     and formatting
        and TABs etc.
  best regards,
   your robot
"""
```
and then  send it like this:

```python
envelope.envelope()\
        .message(body)\
        .subject(subject)\
        .to(email)\
        .sender(smtp_from)\
        .smtp("localhost")\
        .send()
```

But the long body with line breaks gets put into one single line.
How to fix this?

**Comment by e3rd** [comment]
Sorry Aaron, I missed that issue. By default, we are sending HTML mail.

So a quick fix will be to do `body = "\n<br>".join(body.split("\n"))` .
I am planning to add the possibility to send the e-mail in text/plain format too without doubt. But I'm stuck at this decision. There are four possibilities to send the e-mail:
1. text/html (current default)
2. text/plain
3. autodetect if `<br>` or `<p` is in the text → text/html, else text/plain
4. same as 3. + when text/html is used, add text/plain as an alternative


What should be the default behaviour in the next release, 3. or 4.? I'd vote for 3. because that's the way I would expect envelope to work as a developer. ... But there are articles on the net saying it's a good thing to always present a text alternative for your html text.

**Comment by e3rd** [comment]
I've implemented 3. for the while.

Try adding `.mime("plain")` to your envelope object to preserve all the formatting. For the instant, I left "html" as the default and only line breaks are converted automatically `<br>` if forgotten.

**Comment by aaronkaplan** [comment]
Hi!

I think it makes sense to give the user an option. Similar to most mail clients, they also allow the user to select which format should be used by default.
I recommend to set text/plain as the default format.

Best,
a.

**Comment by e3rd** [comment]
You are right. User that writes down plaintext would expect text/plain. Now, user has the control over the mime with the mime function + by default `.mime("auto")` there is a detection whether the message is in HTML. If so, the message has "text/html" but if not, **message keeps text/plain**.
